Pagero UF principally extends http://docs.peppol.eu/poacc/billing/3.0/[PEPPOL BIS Billing 3.0] in two ways:

1. the use of additional segments/elements that are included in UBL 2.1, but excluded from the http://docs.peppol.eu/poacc/billing/3.0/[PEPPOL BIS Billing 3.0]-subset of UBL 2.1.
2. via the use of https://wiki.oasis-open.org/ubl/UBLExtensions[UBL Extensions].

Pagero UF is to be considered as an extension, thus existing EN and Peppol rules may be overriden due to support extended content.

This chapter defines and specifies the available options of *adding information that is not available in the core PEPPOL BIS.* +

The chapter is divided into three parts for easier navigation:

1. <<_invoice>> (specifies segments available on document level)
2. <<_cacinvoiceline>> (specifies segments available on line level)
3. <<_extublextensions>> (Available extensions both on document level and line level)

WARNING: Note that most examples are only shown for document type Invoice.

//=== Parties

//include::parties.adoc[]

=== Invoice

include::documentlevel.adoc[]

=== cac:InvoiceLine

include::linelevel.adoc[]

=== ext:UBLExtensions

include::extensions.adoc[]
