.Elements added in cac:InvoiceLine/cac:TaxTotal
|===
|Path |Description

|`cbc:TaxAmount`
|**Line total tax amount** +
The total tax amount, the sum of the tax subtotals.. +
__Summary of all TaxSubTotal/TaxAmount__
|`cbc:TaxAmount/@currencyID`
|**Line total tax amount currency** +
Line total tax amount currency, must be the same as cbc:DocumentCurrencyCode.
|`cac:TaxSubtotal/cbc:TaxableAmount`
|**Total taxable amount for each tax category** +
Line total taxable amount for each tax category or tax rate. +
__E.g. Summary of all taxable amounts for invoice lines with a certain tax percent.__
|`cac:TaxSubtotal/cbc:TaxableAmount/@currencyID`
|*Total taxable amount for each tax category currency** +
Total taxable amount currency, must be the same as cbc:DocumentCurrencyCode..
|`cac:TaxSubtotal/cbc:TaxAmount`
|**Total tax amount for each tax category** +
Total tax amount for a certain tax category or tax rate.
|`cac:TaxSubtotal/cbc:TaxAmount/@currencyID`
|**Total tax amount currency for each tax category** +
Total tax amount currency, must be the same as cbc:DocumentCurrencyCode.
|`cac:TaxSubtotal/cac:TaxCategory/cbc:ID`
|**Line tax category code** +
Code for identifying the tax category. +
__E.g. tax category "S"__
|`cac:TaxSubtotal/cac:TaxCategory/cbc:Percent`
|**Tax category percent** +
Percentage rate for the tax category.
|`cac:TaxSubtotal/cac:TaxCategory/cbc:TaxExemptionReasonCode`
|**Tax exemption reason code** +
Exemption reason code for the tax category, only applicable if the goods or service is exempt from tax.
|`cac:TaxSubtotal/cac:TaxCategory/cbc:TaxExemptionReason`
|**Tax exemption reason** +
Exemption reason for the tax category, only applicable if the goods or service is exempt from tax.
|`cac:TaxSubtotal/cac:TaxCategory/cac:TaxScheme/cbc:ID`
|**Tax scheme identfier** +
Tax scheme for the tax category, can be either VAT or GST.
|===

*Example* +
_cac:InvoiceLine/cac:TaxTotal example_
[source,xml]
----
<Invoice>
  <!-- Code omitted for clarity -->
  <cac:InvoiceLine>
    <!-- Code omitted for clarity -->
    <cac:TaxTotal>
      <cbc:TaxAmount currencyID="EUR">25.00</cbc:TaxAmount>
      <cac:TaxSubtotal>
          <cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount>
          <cbc:TaxAmount currencyID="EUR">25.00</cbc:TaxAmount>
          <cac:TaxCategory>
              <cbc:ID>S</cbc:ID>
              <cbc:Percent>25</cbc:Percent>
              <cac:TaxScheme>
                  <cbc:ID>VAT</cbc:ID>
              </cac:TaxScheme>
          </cac:TaxCategory>
      </cac:TaxSubtotal>
      <cac:TaxSubtotal>
          <cbc:TaxableAmount currencyID="EUR">-5.00</cbc:TaxableAmount>
          <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
          <cac:TaxCategory>
              <cbc:ID>Z</cbc:ID>
              <cbc:Percent>0</cbc:Percent>
              <cac:TaxScheme>
                  <cbc:ID>VAT</cbc:ID>
              </cac:TaxScheme>
          </cac:TaxCategory>
      </cac:TaxSubtotal>
    </cac:TaxTotal>
    <!-- Code omitted for clarity -->
  </cac:InvoiceLine>
  <!-- Code omitted for clarity -->
</Invoice>
----
